
# Numpy 실습문제



In [2]:
import numpy as np

### 1. 1차원 배열 생성
1부터 20까지의 정수를 원소로 갖는 1차원 배열을 생성하세요.

출력 예시: [ 1 2 3 ... 20]

In [4]:
## 구현
# 힌트: np.arange() 함수를 사용하면 특정 범위의 연속된 숫자를 쉽게 생성할 수 있습니다.
arr = np.arange(1, 21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


### 2. 2차원 배열 생성
0부터 8까지의 정수를 가진 3x3 배열을 생성하세요.

In [5]:
## 구현
# 힌트: np.reshape()를 사용하면 배열의 형태를 원하는 차원으로 바꿀 수 있습니다.
arr = np.arange(9).reshape(3, 3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 3. 배열 연산
다음 배열에 10을 더한 결과를 출력하세요.

In [6]:
arr = np.array([1, 2, 3, 4, 5])
## 구현
# 힌트: 배열에 스칼라(숫자)를 더하면 모든 원소에 자동으로 더해집니다. (브로드캐스팅) 
arr = np.array([1, 2, 3, 4, 5])
result = arr + 10
print(result)

[11 12 13 14 15]


### 4. 형태 변경 (reshape)
1부터 12까지의 숫자로 이루어진 배열을 3x4 형태로 변환하세요.

In [7]:
## 구현
# 힌트: 1차원 배열을 다차원으로 바꿀 때 reshape(행, 열) 사용
arr = np.arange(1, 13).reshape(3, 4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### 5. 슬라이싱
다음 배열에서 짝수 인덱스의 값만 추출하세요.

In [8]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])
## 구현
# 힌트: 짝수 인덱스만 선택하려면 슬라이싱에 step 인자(::2) 사용
arr = np.array([10, 20, 30, 40, 50, 60, 70])
result = arr[::2]
print(result)

[10 30 50 70]


### 6. 불리언 인덱싱
배열에서 50보다 큰 값만 추출하세요.

In [ ]:
arr = np.array([10, 55, 33, 78, 25, 90])
## 구현
# 힌트: 조건문을 배열에 적용해 True/False 마스크 생성 후 필터링
result = arr[arr > 50]
print(result)

[55 78 90]


### 7. 브로드 캐스팅
3x3 배열에 다음 1차원 배열 [1, 2, 3]을 더하세요.

In [10]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

## 구현
# 힌트: 3x3 배열과 1차원 배열 [1,2,3]을 더하면 자동으로 열 단위로 더해짐
add = np.array([1, 2, 3])
result = arr + add
print(result)

[[11 22 33]
 [41 52 63]
 [71 82 93]]


### 8. 조건 대체
배열에서 50 이상인 값은 1, 그렇지 않은 값은 0으로 바꾸세요.

In [11]:
arr = np.array([45, 60, 23, 88, 42])
## 구현
# 힌트: np.where()를 사용하면 조건에 맞는 값을 대체할 수 있습니다.

# 예: np.where(arr >= 20, 3, 1)
result = np.where(arr >= 50, 1, 0)
print(result)

[0 1 0 1 0]


### 9. 기초 통계 연산
다음 배열의 평균, 표준편차, 최댓값, 최솟값을 구하세요.

In [12]:
arr = np.array([5, 15, 25, 35, 45, 55])

## 구현
# 힌트: mean, std, max, min
mean = np.mean(arr)
std = np.std(arr)
max_val = np.max(arr)
min_val = np.min(arr)
print(mean)
print(std)
print(max_val)
print(min_val)

30.0
17.07825127659933
55
5


### 10. 난수 생성 및 조건 필터링
0~100 사이의 정수 난수 20개를 생성하고, 이 중에서 50 이상인 값만 출력하세요.

In [13]:
## 구현
# 힌트: np.random.randint
arr = np.random.randint(0, 101, 20)
filtered = arr[arr >= 50]

print(filtered)

[61 51 79 69 76 69 74 79]


### 11. 행렬 연산
두 2x2 행렬의 곱을 구하세요.

In [15]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

## 구현
# 힌트: np.dot() 또는 @ 연산자
result = np.dot(A, B)  # 또는 A @ B
print(result)

[[19 22]
 [43 50]]


### 12. 정렬과 인덱스 반환
배열을 오름차순으로 정렬하고, 정렬 후의 인덱스를 반환하세요.

In [ ]:
arr = np.array([40, 10, 20, 30])

## 구현
# 힌트: np.sort()를 사용하면 배열을 정렬할 수 있습니다. 
sorted_arr = np.sort(arr)
sorted_indices = np.argsort(arr)

print(sorted_arr)
print(sorted_indices)

[10 20 30 40]
[1 2 3 0]


### 13. 이상치 제거
평균에서 2 표준편차 이상 벗어난 값을 제거하는 코드를 작성하세요.

In [18]:
arr = np.array([10, 12, 13, 120, 15, 14, 200])

## 구현
# 힌트: 평균보다 2 표준편차 작은 값 & 평균보다 2 표준편차 큰 값
mean = np.mean(arr)
std = np.std(arr)
filtered = arr[(arr > mean - 2*std) & (arr < mean + 2*std)]
print(filtered)

[ 10  12  13 120  15  14]


### 14. 정규화(Normalization)
주어진 배열을 0~1 범위로 정규화하세요.

In [19]:
arr = np.array([10, 20, 30, 40, 50])

## 구현
# 힌트: (x-min)/(max-min) 공식을 사용하여 정규화
normalized = (arr - arr.min()) / (arr.max() - arr.min())
print(normalized)

[0.   0.25 0.5  0.75 1.  ]


### 15. 그룹별 평균 계산(데이터 분석)
다음과 같은 데이터에서 성별로 평균 점수를 구하세요.

In [20]:
names = np.array(['Kim', 'Lee', 'Park', 'Choi', 'Jung'])
gender = np.array(['M', 'F', 'M', 'F', 'M'])
scores = np.array([85, 92, 78, 88, 95])

## 구현
# 힌트: 불리언 인덱싱을 사용하여 조건에 맞는 데이터만 선택
male_mean = scores[gender == 'M'].mean()
female_mean = scores[gender == 'F'].mean()

print(male_mean)
print(female_mean)

86.0
90.0


### 16. 상관계수 분석
다음 두 데이터의 상관계수를 구하세요.

In [22]:
x = np.array([10, 20, 30, 40, 50])
y = np.array([15, 25, 35, 45, 55])

## 구현
# 힌트: np.corrcoef(x,y) 함수를 사용하여 상관계수 계산
correlation = np.corrcoef(x, y)[0, 1]
print(correlation)

1.0


### 문제 17: 데이터 요약 통계
난수 100개를 생성하여 평균, 중앙값, 최댓값, 최솟값, 분산을 출력하세요.

In [23]:
## 구현
# 힌트: 난수 생성하는 방법은 np.random.randn(개수) 또는 np.random.randint(최소값, 최대값, 개수)
arr = np.random.randint(0, 100, 100)
mean = np.mean(arr)
median = np.median(arr)
max_val = np.max(arr)
min_val = np.min(arr)
variance = np.var(arr)

print(arr)
print(mean)
print(median)
print(max_val)
print(min_val)
print(variance)

[64 19 74 27 53 21 24  3 11 99 47 14 80 61 38 13 46 42 61 60 34 74 80 87
 61 47 98  2 35 17 14 77 16 57 97 95 48 98 47 73 99 69 29 45 49 85  1 53
  5 44  6 53 98  2 23  5  6 78 54  6 23 92 29 46 85 15 22 94 97 46 61 61
 23 73 47 68 83 71 61 88 26 71 62 67 61 32 94 52 81 84 92 68 98 88 10 78
 71 81 19  6]
52.5
53.5
99
1
895.45
